### ISSUE TITLE
Виділення динамічної пам'яті (calloc, malloc, realloc, new, new[])

### ISSUE THREAD

**Issue by SvyatoS1** [SvyatoS1/Course_preparation_C#10]

**Comment by SvyatoS1** [comment]
#2

**Comment by PrymakBogdan** [comment]
# **Calloc:**
https://learn.microsoft.com/ru-ru/cpp/c-runtime-library/reference/calloc?view=msvc-170
Функція callocвиділяє блок пам'яті й повертає вказівник на перший байт блоку. Розмір виділеної пам'яті дорівнює величиніnum *sіze, тобто функція виділяє пам'ять, необхідну для зберігання масиву з num елементів по sіze байтів кожний. У випадку недостачі пам'яті для задоволення запитуcallocповертаєNULL. Виділена пам'ять ініціалізується нулями.

У C++, функція `calloc` використовується для динамічного виділення блоку пам'яті і ініціалізації його нульовими значеннями. На відміну від оператора `new`, `calloc` є функцією стандартної бібліотеки C і не є частиною операторів мови C++.

Ось приклад використання `calloc`:

```cpp
#include <iostream>
#include <cstdlib> // Для використання calloc

int main() {
    // Виділення пам'яті для масиву з 5 цілих чисел та ініціалізація нульовими значеннями
    int *myArray = static_cast<int*>(calloc(5, sizeof(int)));

    // Перевірка, чи вдалося виділити пам'ять
    if (myArray != nullptr) {
        // Використання виділеної пам'яті

        // Вивід значень (повинно бути 0 для кожного елемента)
        for (int i = 0; i < 5; ++i) {
            std::cout << myArray[i] << " ";
        }

        // Звільнення виділеної пам'яті
        free(myArray);
    } else {
        std::cerr << "Не вдалося виділити пам'ять." << std::endl;
    }

    return 0;
}
```

Функція `calloc` приймає два аргументи: кількість елементів та розмір кожного елемента. Вона повертає вказівник на початок блоку пам'яті.

Важливо відзначити, що для звільнення пам'яті, виділеної `calloc`, використовується функція `free`. Також, перевірка на `nullptr` вказує на те, чи вдалося виділити пам'ять.

# **Malloc:**
Функція malloc здійснює запит на виділення вільної пам'яті з хіпа і, при наявності такої, запитаний обсяг виділяється на потреби програми. Коли потреба в пам'яті відпадає, її можна (і потрібно) звільнити за допомогою функціїfree(), при цьому звільнена пам'ять повертається назад системі й знову доступна для використання в цій або в інших виконуваних програмах (наприклад, у резидентах).

В C++, для динамічного виділення пам'яті використовується оператор `new`. Оператор `new` резервує блок пам'яті в кучі (heap) і повертає вказівник на початок цього блоку. 

Ось простий приклад використання оператора `new` для виділення пам'яті для масиву цілих чисел:

```cpp
#include <iostream>

int main() {
    // Виділення пам'яті для масиву з 5 цілих чисел
    int *myArray = new int[5];

    // Використання виділеної пам'яті
    for (int i = 0; i < 5; ++i) {
        myArray[i] = i * 10;
    }

    // Вивід значень
    for (int i = 0; i < 5; ++i) {
        std::cout << myArray[i] << " ";
    }

    // Звільнення виділеної пам'яті
    delete[] myArray;

    return 0;
}
```

У цьому прикладі `new int[5]` виділяє масив з 5 цілих чисел. Після використання пам'яті важливо її звільнити, щоб уникнути витоку пам'яті. Це робиться за допомогою оператора `delete[]`.

Зверніть увагу, що в C++ також є оператор `new`, який використовується для виділення пам'яті для одного об'єкта (не масиву), і оператори `delete` та `delete[]`, які відповідають за звільнення пам'яті. Неправильне використання цих операторів може призвести до важливих проблем, таких як витік пам'яті або неочікувані помилки.

# **Realloc:**
Функція `realloc` в С++ використовується для зміни розміру блоку пам'яті, який вже був виділений динамічно. Ця функція також може бути використана для динамічного виділення пам'яті, якщо передати `NULL` як перший аргумент.

Ось приклад використання `realloc`:

```cpp
#include <iostream>
#include <cstdlib> // Для використання realloc

int main() {
    // Виділення пам'яті для масиву з 5 цілих чисел
    int *myArray = static_cast<int*>(malloc(5 * sizeof(int)));

    // Перевірка, чи вдалося виділити пам'ять
    if (myArray != nullptr) {
        // Використання виділеної пам'яті

        // Змінення розміру масиву на 10 цілих чисел
        int *newArray = static_cast<int*>(realloc(myArray, 10 * sizeof(int)));

        // Перевірка, чи вдалося змінити розмір пам'яті
        if (newArray != nullptr) {
            // Використання зміненої пам'яті

            // Звільнення виділеної пам'яті (новий масив збереже дані)
            newArray = nullptr;
        } else {
            std::cerr << "Не вдалося змінити розмір пам'яті." << std::endl;
            // Збереження оригінального вказівника у випадку невдалої зміни розміру
            free(myArray);
        }
    } else {
        std::cerr << "Не вдалося виділити пам'ять." << std::endl;
    }

    return 0;
}
```

Функція `realloc` приймає два аргументи: вказівник на блок пам'яті, який потрібно змінити, і новий розмір блоку пам'яті. Вона повертає вказівник на новий блок пам'яті. Якщо зміна розміру не вдалася, вона повертає `nullptr`. У випадку вдалої зміни розміру, пам'ять, що була виділена раніше, автоматично звільняється, і новий блок пам'яті може бути використаний.

# **New:**

У C++, оператор `new` використовується для динамічного виділення пам'яті. Він повертає вказівник на виділений блок пам'яті. При використанні `new`, ви можете створити об'єкт або масив об'єктів на кучі (heap).

Ось простий приклад використання оператора `new` для виділення пам'яті для одного об'єкта та масиву об'єктів:

```cpp
#include <iostream>

class MyClass {
public:
    MyClass() {
        std::cout << "Конструктор MyClass" << std::endl;
    }

    ~MyClass() {
        std::cout << "Деструктор MyClass" << std::endl;
    }
};

int main() {
    // Виділення пам'яті для одного об'єкта класу MyClass
    MyClass *obj = new MyClass;

    // Виділення пам'яті для масиву з трьох об'єктів класу MyClass
    MyClass *arr = new MyClass[3];

    // Використання виділеної пам'яті

    // Звільнення пам'яті для одного об'єкта
    delete obj;

    // Звільнення пам'яті для масиву
    delete[] arr;

    return 0;
}
```

У цьому прикладі `new MyClass` виділяє пам'ять для одного об'єкта класу `MyClass`, а `new MyClass[3]` виділяє пам'ять для масиву з трьох об'єктів. Після використання цієї пам'яті, важливо викликати `delete` для одного об'єкта та `delete[]` для масиву, щоб уникнути витоку пам'яті.

Якщо ви використовуєте `new`, ви повинні також використовувати `delete` або `delete[]` відповідно для звільнення виділеної пам'яті і запобігання проблемам з витоком пам'яті.

# **New[]:**

В C++, оператор `new[]` використовується для динамічного виділення пам'яті для масиву об'єктів. Підтримується виділення пам'яті для масивів з будь-яким типом даних. При використанні `new[]`, ви можете створити масив об'єктів на кучі (heap).

Ось приклад використання оператора `new[]`:

```cpp
#include <iostream>

class MyClass {
public:
    MyClass() {
        std::cout << "Конструктор MyClass" << std::endl;
    }

    ~MyClass() {
        std::cout << "Деструктор MyClass" << std::endl;
    }
};

int main() {
    // Виділення пам'яті для масиву з п'яти об'єктів класу MyClass
    MyClass *myArray = new MyClass[5];

    // Використання виділеної пам'яті

    // Звільнення пам'яті для масиву
    delete[] myArray;

    return 0;
}
```

У цьому прикладі `new MyClass[5]` виділяє пам'ять для масиву з п'яти об'єктів класу `MyClass`. Після використання цієї пам'яті, важливо викликати `delete[]`, щоб правильно звільнити виділену пам'ять для всього масиву. Виклик деструкторів для кожного об'єкта в масиві також буде автоматично викликаний при виклику `delete[]`.

Користуйтеся `delete[]` завжди, коли використовуєте `new[]`, і використовуйте `delete` для `new`. Звільнення пам'яті правильним чином важливо для уникнення витоку пам'яті та збереження коректної роботи програми.
