### ISSUE TITLE
Reference vs Pointer

### ISSUE THREAD

**Issue by SvyatoS1** [SvyatoS1/Course_preparation_C#12]

**Comment by PrymakBogdan** [comment]
#2 
# **ПОСИЛАННЯ**
   Посилання це простий тип даних, який менш потужній, але більш безпечний ніж вказівник
. Тип посилання іноді називається аліасом, і слугує для створення об’єкту додаткового імені. Посилання дозволяє маніпулювати об'єктом так само, як це робиться за допомогою вказівника, однак це не потребує спеціального синтаксису, яке необхідне при роботі з вказівниками.
C++ посилання мають наступні відмінності в порівнянні з вказівниками:
- На відміну від вказівника, посилання повинно бути ініціалізоване не адресою об'єкту, а його значенням.
- Не можливо звернутися на пряму до об'єкту посилання, після того як він був визначений; будь-яке входження його імені звертається безпосередньо до об'єкту, на який воно посилається.
- Після того як посилання було створене, посилання не можливо змінити так, щоб воно почало вказувати на інший об'єкт; Воно не може бути змінено. З вказівниками це можливо зробити.
- Посилання не може бути пустим, тобто приймати значення null, в той час як вказівники можуть; Кожне посилання звертається до якогось об'єкту, хоча він може не бути дійсним. З цієї причини, контейнери з посиланнями не дозволені.
- Посилання повинно бути ініціалізованим. Оскільки не можливо змінити посилання, воно повинно бути ініціалізоване, як тільки воно було об’явлене. Зокрема локальні і глобальні змінні потрібно ініціалізувати одразу при їх об’явленні, а посилання, які є полями класу мають бути ініціалізовані в списку ініціалізації конструктора класу. Наприклад:
`int& k; // Помилка: k об’явлено як посилання, але не є визначеним`
   Посилання зазвичай поводяться ідентично значенням, на які вони посилаються. У цьому сенсі посилання працює як псевдонім об’єкта, на який воно посилається, наприклад:
```
#include <iostream>
 
int main()
{
	int value = 7; // звичайна змінна
	int &ref = value; // посилання на змінну value
 
	value = 8; // value тепер 8
	ref = 9; // value тепер 9
 
	std::cout << value << std::endl; // виведеться 9
	++ref;
	std::cout << value << std::endl; // виведеться 10
 
	return 0;
}
```

   Не можна ініціалізувати неконстантне посилання константним об’єктом. В іншому випадку, ви б могли змінити значення константного об’єкта через посилання, що вже порушує саме поняття «константа».


   Посилання найчастіше використовуються в якості параметрів у функціях. У цьому контексті посилання-параметр працює як псевдонім аргументу, а сам аргумент не копіюється при передачі в параметр. Це в свою чергу підвищує продуктивність, якщо аргумент занадто великий або витратний для копіювання. Посилання працюють аналогічно вказівникам. Оскільки посилання-параметр — це псевдонім аргументу, то функція, яка використовує посилання-параметр, може змінювати аргумент, переданий їй, також напряму:
```
#include <iostream>
 
// ref - це посилання на переданий аргумент, а не копія аргументу
void changeN(int &ref)
{
	ref = 8;
}
 
int main()
{
	int x = 7;
 
	std::cout << x << '\n';
 
	changeN(x); // зверніть увагу, цей аргумент не обов'язково повинен бути посиланням
 
	std::cout << x << '\n';
	return 0;
}
```
   Оскільки посилання повинні бути ініціалізовані коректними об’єктами (вони не можуть бути нульовими) і не можуть бути змінені пізніше, то вони, як правило, є безпечнішими за вказівники (так як ризик розіменування нульового вказівника відпадає). Однак, вони трохи обмежені в функціональності в порівнянні з вказівниками.
 
   Якщо поставлене завдання можна вирішити за допомогою як посилань, так і вказівників, то краще використовувати посилання. Вказівники слід використовувати тільки в тих ситуаціях, коли посилання є недостатньо ефективними (наприклад, при динамічному виділенні пам’яті).

**Comment by PrymakBogdan** [comment]
## Вказівники корисні в наступних випадках:

   Випадок №1: Масиви реалізовані за допомогою вказівників. Вказівники можуть використовуватися для ітерації по масиву.

   Випадок №2: Вони є єдиним способом динамічного виділення пам’яті в С++. Це, безумовно, найбільш поширений варіант використання вказівників.

   Випадок №3: Вони можуть використовуватися для передачі великої кількості даних в функцію без копіювання цих даних.

   Випадок №4: Вони можуть використовуватися для передачі однієї функції в якості параметру іншій функції.

   Випадок №5: Вони використовуються для досягнення поліморфізму при роботі зі спадкуванням.

   Випадок №6: Вони можуть використовуватися для представлення однієї структури/класу в іншій структурі/класі, формуючи, таким чином, “ланцюжки”.
