### ISSUE TITLE
OOP: Virtual, таблиця віртуальних методів, віртуальні функції

### ISSUE THREAD

**Issue by SvyatoS1** [SvyatoS1/Course_preparation_C#15]

**Comment by PrymakBogdan** [comment]
# Віртуальні функції
Віртуальна функція в мові С++ — це особливий тип функції, яка, при її виклику, виконує «найдочірніший» метод, який існує між батьківським і дочірніми класами. Ця властивість відома як поліморфізм. Дочірній метод викликається тоді, коли збігається сигнатура (ім’я, типи параметрів і чи є метод константним) і тип повернення дочірнього методу з сигнатурою і типом повернення методу батьківського класу. Такі методи називаються перевизначеннями (або “перевизначеними методами”).
- _Попередження: Сигнатура віртуального методу дочірнього класу повинна повністю відповідати сигнатурі віртуального методу батьківського класу. Якщо у дочірнього методу буде інший тип параметрів, ніж у батьківського, то викликатися цей метод не буде._
- _Не викликайте віртуальні функції в тілі конструкторів або деструкторів_
«Якщо все так добре з віртуальними функціями, то чому б не зробити всі методи віртуальними?» — запитаєте Ви. Відповідь: “Це неефективно!”. Обробка і виконання виклику віртуального методу займає більше часу, ніж обробка і виконання виклику звичайного методу. Крім того, компілятор також повинен виділяти один додатковий вказівник для кожного об’єкта класу, який має одну або кілька віртуальних функцій.
```
#include <iostream>
 
class Parent
{
public:
    virtual const char* getName() { return "Parent"; } // додали ключове слово virtual
};
 
class Child: public Parent
{
public:
    virtual const char* getName() { return "Child"; }
};
 
int main()
{
    Child child;
    Parent &rParent = child;
    std::cout << "rParent is a " << rParent.getName() << '\n';
 
    return 0;
}
```
 Джерело: https://acode.com.ua/urok-171-virtualni-funktsiyi-i-polimorfizm/

**Comment by PrymakBogdan** [comment]
# Таблиці віртуальних методів
Віртуальна таблиця в мові С++ — це таблиця пошуку функцій для виконання викликів функцій в режимі пізнього (динамічного) зв’язування. Віртуальну таблицю ще називають «vtable» або «таблицею віртуальних функцій/методів».

По-перше, будь-який клас, який використовує віртуальні функції (або дочірній клас, батьківський клас якого використовує віртуальні функції), має свою власну віртуальну таблицю. Це звичайний статичний [масив](https://acode.com.ua/urok-77-masyvy/), який створюється компілятором під час компіляції. Віртуальна таблиця містить по одному запису на кожну віртуальну функцію, яка може бути викликана об’єктами класу. Кожен запис в цій таблиці — це [вказівник на функцію](https://acode.com.ua/urok-110-vkazivnyky-na-funktsiyi/), який вказує на “найдочірніший” метод, доступний об’єкту цього класу.

По-друге, компілятор також додає прихований вказівник на батьківський клас, який ми називатимемо *__vptr. Цей вказівник автоматично створюється при створенні об’єкта класу і вказує на віртуальну таблицю цього класу. На відміну від [прихованого вказівника *this](https://acode.com.ua/urok-129-pryhovanyj-vkazivnyk-this/), який фактично є параметром функції, який компілятор використовує для “вказівки на самого себе”, *__vptr є реальним вказівником. Отже, розмір кожного об’єкта збільшується на розмір цього вказівника. *__vptr також успадковується дочірніми класами.

```
class Parent
{
public:
    virtual void function1() {};
    virtual void function2() {};
};
 
class C1: public Parent
{
public:
    virtual void function1() {};
};
 
class C2: public Parent
{
public:
    virtual void function2() {};
};
```
Тут у нас є 3 класи, відповідно, компілятор створить 3 віртуальні таблиці: одна для Parent, одна для C1 і одна для C2.
Компілятор також додасть прихований вказівник на головний батьківський клас з віртуальними функціями. Хоча компілятор робить це автоматично, ми покажемо, де цей вказівник додається:

```
class Parent
{
public:
    FunctionPointer *__vptr; // тут
    virtual void function1() {};
    virtual void function2() {};
};
 
class C1: public Parent
{
public:
    virtual void function1() {};
};
 
class C2: public Parent
{
public:
    virtual void function2() {};
};
```
За допомогою віртуальних таблиць компілятор і програма можуть гарантувати, що виклики функцій викликатимуть відповідні віртуальні функції/перевизначення, навіть якщо ви використовуватимете тільки вказівник або посилання на батьківський клас!

Виклик віртуальної функції відбувається повільніше, ніж виклик невіртуальної функції, тому що:

   По-перше, ми повинні використовувати *__vptr для переходу до відповідної віртуальної таблиці.

   По-друге, ми повинні індексувати віртуальну таблицю, щоб знайти правильну функцію для виклику.

   І тільки тепер ми зможемо виконати виклик функції.

В результаті ми робимо 3 операції, щоб викликати функцію, на відміну від двох операцій для звичайного непрямого виклику функції або однієї операції для прямого виклику функції. Однак для сучасних комп’ютерів витрачений додатковий час не є значним.

Джерело: https://acode.com.ua/urok-175-virtualni-tablytsi/

**Comment by PrymakBogdan** [comment]
В програмі буде стільки віртуальних таблиць методів, скільки існує класів з віртуальними методами (функціями).
