### ISSUE TITLE
Процес, потік і файл

### ISSUE THREAD

**Issue by SvyatoS1** [SvyatoS1/Course_preparation_C#19]

**Comment by SvyatoS1** [comment]
#17

**Comment by PrymakBogdan** [comment]
# Процеси
Процес - це об'єкт ОС Linux, який складається з адресного простору пам'яті і набору структур даних. По суті, процес це запущена програма або служба. Кожен запущений процес в ОС Linux може породити додаткові процеси. Процес, що запустив новий процес називається батьківським процесом. Новий процес по відношенню до створив його процесові називається дочірнім. Процеси - це не те ж саме, що завдання: процеси є частиною операційної системи, тоді як про завдання відомо тільки командному процесору, в якому вони виконуються. Працююча програма містить в собі один або більше процесів; завдання складається з однієї або більше програм, виконуваних у вигляді команд командного процесора. Кожен процес в ОС Linux характеризується набором атрибутів, який відрізняє даний процес від всіх інших процесів. 
До головних атрибутів відносяться:

- Ідентифікатор процесу (PID). Кожен процес в системі має унікальний ідентифікатор. Кожен новий запущений процес отримує номер на одиницю більше попереднього.
- Ідентифікатор батьківського процесу (PPID). Даний атрибут процес отримує під час свого запуску та використовується для отримання статусу батьківського процесу.

У Linux процеси діляться на три типи: 
- Системні процеси - є частиною ядра і завжди розташовані в оперативній пам'яті. Системні процеси не мають відповідних їм програм у вигляді виконуваних файлів і запускаються при ініціалізації ядра системи. Виконувані інструкції і дані цих процесів знаходяться в ядрі системи, таким чином, вони можуть викликати функції і звертатися до даних, недоступним для інших процесів. Системними процесами, наприклад, є: shed (диспетчер свопінгу), vhand (диспетчер сторінкового заміщення), kmadaemon (диспетчер пам'яті ядра). 
- Демони - це неінтерактивні процеси, які запускаються звичайним чином - шляхом завантаження в пам'ять відповідних їм програм (виконуваних файлів), та виконується у фоновому режимі. Зазвичай демони запускаються при ініціалізації системи (але після ініціалізації ядра) і забезпечують роботу різних підсистем: системи термінального доступу, системи друку, система мережевого доступу і мережевих послуг, поштовий сервер, dhcp-сервер і т. п. Демони не пов'язані ні з одним користувальницьким сеансом роботи і не можуть безпосередньо управлятися користувачем. Велику частину часу демони чекають поки той або інший процес запросить певну послугу, наприклад, доступ до файлового архіву або друк документа. 
- Прикладні (користувальницькі) процеси. До прикладних процесів належать всі інші процеси, що виконуються в системі. Як правило, це процеси, породжені в рамках користувальницького сеансу роботи. Наприклад, команда ls породить відповідний процес цього типу. Прикладні процеси linux можуть виконуватися як в інтерактивному, так і у фоновому режимі, але в будь-якому випадку час їхнього життя (і виконання) обмежена сеансом роботи користувача. При виході з системи всі прикладні процеси будуть знищені.

**Comment by PrymakBogdan** [comment]
# Потоки
Потоки виконання здійснюють операції всередині процесу. У них є лічильник команд, стек їх виконання і набір регістрів. Ядро системи працює з потоками, а не з процесами. 

Потоком (потік керування, нитка, thread) називають набір послідовно виконуваних команд процесора, які використовують загальний адресний простір процесу. Оскільки в системі може одночасно бути багато потоків, завданням ОС є організація перемикання процесора між ними і планування їхнього виконання. У багатопроцесорних системах код окремих потоків може виконуватися на окремих процесорах. Тепер можна дати ще одне означення процесу. Процесом називають сукупність одного або декількох потоків і захищеного адресного простору, у якому ці потоки виконуються.
 На відміну від процесів потоки розпоряджаються загальною пам’яттю. Дані потоку не захищені від доступу до них інших потоків за умови, що всі вони виконуються в адресному просторі одного процесу.
До елементів процесу належать:

- захищений адресний простір;
- дані, спільні для всього процесу (ці дані можуть спільно використовувати всі його потоки);
- інформація про використання ресурсів (відкриті файли, мережні з’єднання тощо);
- інформація про потоки процесу.
- 
Потік містить такі елементи:

- стан процесора (набір поточних даних із його регістрів), зокрема лічильник поточної інструкції процесора;
- стек потоку (ділянка пам’яті, де перебувають локальні змінні потоку й адреси повернення функцій, що викликані у його коді).

Перш ніж розглянути основні підходи до реалізації моделі потоків, дамо означення важливих понять потоку користувача і потоку ядра. Потік користувача — це послідовність виконання команд в адресному просторі процесу. Ядро ОС не має інформації про такі потоки, вся робота з ними виконується в режимі користувача.

Потік ядра — це послідовність виконання команд в адресному просторі ядра. Потоками ядра управляє ОС, перемикання ними можливе тільки у привілейованому режимі. Є потоки ядра, які відповідають потокам користувача, і потоки, що не мають такої відповідності. Співвідношення між двома видами потоків визначає реалізацію моделі потоків.

**Comment by SvyatoS1** [comment]
### Файл
Основний спосіб для зберігання та організації даних на операційних системах (OS). У багатьох ОС файл використовується як основна одиниця для зберігання інформації, незалежно від того, чи є це текстовий документ, програмний код, медіафайл чи будь-які інші дані. У С++, взаємодія з файлами здійснюється за допомогою стандартної бібліотеки `<fstream>`.

Отже, ось детальніше про файли в операційних системах та їх використання в С++:

1. **Операційні системи та файли:**
   - В ОС файл є основною одиницею організації даних. Кожен файл має унікальне ім'я, тип, розмір та шлях до нього.
   - Файли можуть бути розташовані на різних носіях, таких як жорсткі диски, SSD, флеш-накопичувачі, мережеві сховища тощо.
   - Операційні системи надають API та інтерфейси для роботи з файлами, такі як функції для відкриття, читання, запису, закриття тощо.
   - Кожний файл має свої атрибути, такі як дозволи на доступ, дата та час створення, зміни, останнього доступу тощо.

2. **С++ та робота з файлами:**
   - У С++ взаємодія з файлами відбувається за допомогою бібліотеки `<fstream>`.
   - У цій бібліотеці є класи `ifstream`, `ofstream` та `fstream`, які відповідають за читання, запис та одночасне читання/запис файлів відповідно.
   - Основні операції з файлами включають відкриття файлу, читання з файлу, запис у файл, закриття файлу.
   - Ось простий приклад відкриття файлу за допомогою бібліотеки `<fstream>`:

    ```cpp
    #include <iostream>
    #include <fstream>

    int main() {
        std::ifstream file("example.txt");
        if (file.is_open()) {
            std::cout << "Файл успішно відкрито\n";
            // Виконати операції з файлом
            file.close();
        } else {
            std::cerr << "Не вдалося відкрити файл\n";
        }
        return 0;
    }
    ```

   - У цьому прикладі програма використовує `ifstream` для відкриття файлу "example.txt" для читання. Якщо файл вдалося відкрити, програма виводить повідомлення про успішне відкриття файлу.

Отже, файли в операційних системах та С++ є ключовими компонентами для зберігання та обробки даних. З їх допомогою можна здійснювати різноманітні операції з інформацією, яка використовується в програмах та системах.

**Comment by PrymakBogdan** [comment]
# Файли
В linux все = файл


В операційній системі Linux, робота з файлами є однією з основних операцій для взаємодії з системою. Файли в Linux можуть бути текстовими, виконуваними, каталогами, символічними посиланнями, тощо. Ось деякі ключові поняття та операції, пов'язані з роботою з файлами в Linux:

1. **Шляхи (Paths):** У Linux файли і каталоги ідентифікуються шляхами. Шлях може бути абсолютним (починається з кореневого каталогу, наприклад, `/home/user/document.txt`) або відносним (відносно поточного робочого каталогу).

2. **Типи файлів:**
   - **Звичайні файли:** Зберігають інформацію (текст, бінарні дані).
   - **Директорії (каталоги):** Зберігають вказівники на інші файли та каталоги.
   - **Символічні посилання (symlinks):** Вказівники на інші файли або директорії.
   - **Спеціальні файли:** Наприклад, файли символьних та блочних пристроїв або сокетів.

3. **Основні операції з файлами в командному рядку:**
   - `ls`: Перелік файлів та каталогів в поточному каталозі.
   - `cp`: Копіювання файлів або каталогів.
   - `mv`: Переміщення або перейменування файлів.
   - `rm`: Видалення файлів або каталогів.
   - `mkdir`: Створення нового каталогу.
   - `cat`: Виведення вмісту текстового файлу в консоль.
   - `less` або `more`: Перегляд текстового файлу сторінка за сторінкою.

4. **Робота з правами доступу:**
   - Кожен файл має власника та групу.
   - Визначається три види прав доступу: читання (`r`), запис (`w`), виконання (`x`).
   - Права доступу можна налаштовувати за допомогою команди `chmod`.

5. **Робота з текстовими редакторами:**
   - `nano`, `vim`, `emacs`: Текстові редактори, які можна використовувати з командного рядка для редагування файлів.

6. **Спеціальні символи в шляхах:**
   - `.`: Поточний каталог.
   - `..`: Батьківський каталог.
   - `~`: Домашній каталог поточного користувача.

7. **Спеціальні команди для роботи з файловою системою:**
   - `df`: Відображення інформації про вільний простір на файловій системі.
   - `du`: Вимірювання використаного простору на файловій системі.
   - `find`: Пошук файлів за різними критеріями.

Це лише загальний огляд. Командна робота з файлами в Linux може бути вдосконалена і розширена за допомогою різних утиліт і функцій операційної системи.
