### ISSUE TITLE
Compilation process: preprocessor, type checker, compiler, assembly, linker

### ISSUE THREAD

**Issue by SvyatoS1** [SvyatoS1/Course_preparation_C#21]
#20

**Comment by PrymakBogdan** [comment]
![Image](https://github.com/SvyatoS1/Course_preparation_C/assets/152421548/e4bda8b6-eadf-4f29-bbea-3aec4a5a343e)

Процес компіляції включає кілька етапів, які перетворюють вихідний код програми з високорівневого мови програмування в виконуваний код, який можна запустити на конкретній архітектурі. Зазвичай, процес компіляції складається з наступних етапів:

1. **Препроцесор (Preprocessor):**
   - **Мета:** Обробка вихідного коду перед власне компіляцією.
   - **Основні дії:**
     - Обробка директив препроцесора, таких як `#include`, `#define`, `#ifdef`.
     - Вставка вмісту файлів, вказаних директивою `#include`.
     - Виконання макропідстановок за допомогою директиви `#define`.
     - Видалення коментарів.


2. **Компіляція (Compilation):**
   - **Мета:** Перетворення вихідного коду, який написаний мовою програмування, у мову асемблера або машинний код.
   - **Основні дії:**
     - Синтаксичний аналіз та перетворення вихідного коду у проміжний код або машинний код.
     - Оптимізація коду для поліпшення швидкодії або зменшення об'єму виконуваного коду.

3. **Асемблювання (Assembly):**
   - **Мета:** Перетворення машинного коду (або проміжного коду) в об'єктний код, який може бути зрозумілий асемблером.
   - **Основні дії:**
     - Преобразування машинного коду, створеного компілятором, в асемблерний код.

4. **Компонування (Linking):**
   - **Мета:** Об'єднання об'єктних файлів та бібліотек у виконуваний файл.
   - **Основні дії:**
     - Об'єднання об'єктних файлів, створених на попередньому етапі.
     - Розв'язування символів та створення таблиці символів.
     - Вирішення викликів функцій та зовнішніх змінних.
     - Формування виконуваного файлу, який може бути запущений на виконання.

Під час компіляції можуть виникати помилки на різних етапах. Компілятор генерує повідомлення про помилки або попередження, які можна використовувати для виправлення проблем вихідного коду.

Важливо зауважити, що в окремих випадках можуть бути застосовані інші інструменти та етапи, такі як оптимізація на рівні асемблера, генерація проміжного коду тощо. Компіляція - це складний процес, який дозволяє перетворити вихідний код в готовий до виконання виконуваний файл.
