### ISSUE TITLE
Мейкфайли (шо це, для чого)

### ISSUE THREAD

**Issue by SvyatoS1** [SvyatoS1/Course_preparation_C#24]
#20

**Comment by PrymakBogdan** [comment]
# Мейкфайл 
— це текстовий файл, який містить набір правил та інструкцій для автоматизації процесу збірки (компіляції) програми чи проекту. Головна мета мейкфайлу — визначити, які файли в проекті повинні бути перекомпільовані та як це робити.

`make [-f make-файл] [опції]... [адресати]...`

Основні поняття та елементи мейкфайлу:

1. **Ціль (Target):**
   - Це об'єкт, який має бути створений. Ціль може бути виконуваним файлом, об'єктним файлом, бібліотекою або будь-яким іншим об'єктом, який потрібно отримати після збірки.

2. **Залежності (Dependencies):**
   - Це файли або цілі, від яких залежить вихідна ціль. Якщо якась залежність змінюється, це може вплинути на ціль, і, отже, ціль потрібно перекомпілювати.

3. **Правило (Rule):**
   - Це інструкція, яка визначає, як створити ціль з вихідних файлів та залежностей. Вона містить команди для компіляції, лінкування, копіювання тощо.

4. **Змінні (Variables):**
   - Змінні використовуються для зберігання значень, таких як імена компілятора, опції компіляції, шляхи до каталогів тощо. Вони дозволяють зробити мейкфайл більш гнучким і зручним для конфігурації.

5. **Мети (Goals):**
   - Це конкретні цілі, які можна вказати для виклику в процесі використання мейкфайлу. Зазвичай це назва виконуваного файлу чи об'єкта.

6. **Команди (Commands):**
   - Команди вказують, як створити ціль. Вони виконуються у командному рядку і зазвичай містять інструкції компіляції, лінкування та інші дії.

### Для чого використовують мейкфайли:

1. **Автоматизація збірки:**
   - Мейкфайли дозволяють визначити правила для автоматичної збірки проекту без необхідності вручну вводити команди компіляції.

2. **Ефективність:**
   - Завдяки мейкфайлам відбувається перекомпіляція тільки тих файлів, які зазнали змін, що зменшує час збірки та оптимізує процес розробки.

3. **Легка підтримка проектів:**
   - З допомогою мейкфайлів легше підтримувати та розширювати проекти. Вони дозволяють визначати структуру проекту, робити його складнішим чи простішим для збірки.

4. **Платформо-незалежність:**
   - Мейкфайли можуть бути сконфігуровані для роботи на різних операційних системах та архітектурах, що дозволяє легше переміщати проекти між різними середовищами.

Приклад мейкфайлу може виглядати приблизно так:

```make
CC = gcc
CFLAGS = -Wall -O2
TARGET = my_program

all: $(TARGET)

$(TARGET): main.o utils.o
	$(CC) $(CFLAGS) -o $@ $^

main.o: main.c
	$(CC) $(CFLAGS) -c $<

utils.o: utils.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(TARGET) *.o
```

У цьому прикладі мейкфайл вказує, що програма `my_program` залежить від файлів `main.o` та `utils.o`. Команди для компіляції та лінкування визначені у відповідних правилах.

Ключі
-b :

-m : Ці ключі ігноруються заради сумісності з іншими версіями make.

-C каталог : Перейти до вказаного каталогу перед читанням make-файлів або здійсненням інших дій. Якщо задано декілька опцій -C, кожна інтерпретується відносно попередньої: -C / -C /etc рівнозначне -C /etc. Типово, використовується для рекурсивних викликів make.

-d : Вивести інформацію зневадження, наряду зі звичайною обробкою. Зневаджувальні повідомлення вказують, які файли необхідно оновити, які мітки часу порівнюються, які файли перекомпільовано, які правила застосовано - словом, все, що може видатись цікавим щодо операцій, здійснюваних make.

-f файл : Використати файл як make-файл.

-i : Ігнорує всі помилки команд, виконаних для оновлення файлів.

-I каталог : Вказує каталог для пошуку там make-файлів. Якщо використати декілька опцій -I, пошук здійснюватиметься у вказаному порядку. На відміну від аргументів решти прапорців make, каталоги, що стоять після -I можна друкувати одразу після прапорця, тобто дозволяється -Iкаталог, так само як -I каталог. Такий синтаксис передбачено для сумісності з прапорцем -I препроцесору C.

-j завдань : Вказує кількість завдань (команд), що можна одночасно запустити. Якщо існує більше однієї опції -j, остання візьме гору. Якщо ж вказати -j без аргументу, кількість процесів не обмежуватиметься.

-k : Продовжити, наскільки це можливо після помилки. Навіть, якщо адресат і те, що залежить від нього не можна перезібрати, решта взаємозалежностей цих адресатів буде оброблено як звичайно.

-l :

-l навантаження : Не розпочинатиме жодних завдань (команд), якщо виконуються інші, і середнє навантаження системи, щонайменше дорівнює вказаному (числу з плаваючою точкою). Без жодних аргументів, скасовує попереднє обмеження навантаження.

-n : Виведе команди, які би було виконано, але не виконуватиме їх.

-o файл : Не чіпати файл, навіть якщо він старший за залежні від нього, так само не перезбирати нічого, пов'язаного зі змінами у файлі. Фактично, файл вважатиметься дуже старим, і його правила ігноруватимуться.

-p : Виведе дані make-файлу (правила і значення змінних), після чого продовжити звичайне виконання, або таке, яке вказано. Це також виводить інформацію про версію make, ніби було вжито ключ -v (дивіться нижче). Щоб вивести дані make-файлу, без перезібрання, скористайтеся з "make -p -f/dev/null".

-q : Режим запиту. Не виконувати жодних команд, або виводити що-небудь; просто повернути статус рівний нулю, якщо адресати осучаснені, і ненульовий статус, якщо ні.

-r : Скасує використання вбудованих, прихованих правил. Також очистить стандартний список суфіксів, вживаних у суфіксних правилах.

-s : Безмовний режим; не друкуватиме команд під час їхнього виконання.

-S : Скасовує дію ключа -k. В цьому, звичайно, немає необхідності, за винятком рекурсивного make, де -k, можливо, успадковано від попереднього make рівнем вище, зі встановленою змінною MAKEFLAGS, або коли MAKEFLAGS вашого середовища включає -k.

-t : Зачіпає файли (помічає їх як сучасні, не змінюючи їх насправді), замість виконати, внесені там команди. Це застосовується для удавання, ніби команди було виконано, для того, щоб обманути наступні виклики make.

-v : Виводить версію програми make, а також авторські права, список авторів, і попередження про відсутність гарантії.

-w : Виведе повідомлення з вказівкою робочого каталогу до і після іншої обробки. Це може виявитись корисним для виявлення помилок під час складного гніздування, або рекурсивних викликів make.

-W файл : Прикинутись, ніби адресований файл щойно модифіковано. При використанні з прапорцем -n, це продемонструє, що би сталося, якби ви змінили цей файл. Без -n, це рівнозначно виконанню команди [touch(1)](https://docs.linux.org.ua/man/man1/touch.1/) перед запуском make, за винятком того, що час модифікації змінено тільки в уяві make .
