### ISSUE TITLE
Пару протоколів розберись: TCP, IP, DHCP, DNS.

### ISSUE THREAD

**Issue by PrymakBogdan** [SvyatoS1/Course_preparation_C#27]

**Comment by PrymakBogdan** [comment]
#25

**Comment by SvyatoS1** [comment]
- ## Вступ
TCP/IP, DHCP і DNS є найбільш використовуваними протоколами у сучасних комп'ютерних мережах. Цей повний мануал надасть глибоке розуміння кожного протоколу та їх ролі у структурі мережі.

- # Частина 1: TCP/IP (Transmission Control Protocol/Internet Protocol)
- ## 1.1 TCP (Transmission Control Protocol)
TCP - це протокол транспортного рівня, який забезпечує надійну, послідовну та орієнтовану на з'єднання передачу даних між пристроями. Основні характеристики включають:
 Надійність: Впевнення, що дані будуть доставлені без втрат або дублювання.
Установлення та Розрив З'єднання: Можливість створення та завершення з'єднань між пристроями.


![Image](https://github.com/SvyatoS1/Course_preparation_C/assets/107581459/cf972af5-a982-4cf5-b6c9-2921380443a3)


- ## 1.2 IP (Internet Protocol)
IP - це протокол мережевого рівня, відповідальний за адресацію та маршрутизацію пакетів даних в мережі. Основні аспекти:
IP-адреси: Унікальні ідентифікатори пристроїв у мережі.
Маршрутизація: Процес визначення шляху, яким повинні йти пакети від відправника до отримувача.
- # Частина 2: DHCP (Dynamic Host Configuration Protocol)
- ## 2.1 DHCP (Dynamic Host Configuration Protocol)
DHCP - це протокол, який дозволяє автоматично надавати мережеві конфігурації пристроям у мережі. Важливі аспекти:


![Image](https://github.com/SvyatoS1/Course_preparation_C/assets/107581459/6ebf46cf-047f-4cc3-8618-99e087ea17a3)


Динамічна Адресація: Автоматичне отримання IP-адреси та інших параметрів мережі.
Менеджмент Адрес: Забезпечення унікальності та відстеження використаних IP-адрес.
- # Частина 3: DNS (Domain Name System)
- ## 3.1 DNS (Domain Name System)
DNS - це протокол, який перетворює людські читабельні доменні імена в IP-адреси. Основні елементи:


![Image](https://github.com/SvyatoS1/Course_preparation_C/assets/107581459/3239385d-8613-41d5-9fa6-7688739d9e64)


Доменні Імена: Ідентифікатори пристроїв у зручній для людини формі.
Розподіленій Запис Даних: Розподілена база даних, що перетворює доменні імена в IP-адреси.
- # Частина 4: Практичний Застосунок
- ## 4.1 З'єднання TCP/IP, DHCP та DNS
Запитання IP-адреси через DHCP: Пристрої автоматично отримують IP-адреси та інші конфігураційні дані від сервера DHCP.
Використання DNS для Резолюції Доменних Імен: Пристрої використовують DNS для знаходження IP-адрес за доменними іменами.
- ## Заключення
Цей повний мануал розкриває основні протоколи TCP/IP, DHCP і DNS, які використовуються для побудови та управління сучасними комп'ютерними мережами. Розуміння їхньої роботи та взаємозв'язку допомагає забезпечити ефективну та надійну роботу мережевих інфраструктур.
