### ISSUE TITLE
Робота з масивами, вказівниками, стрінгами

### ISSUE THREAD

**Issue by SvyatoS1** [SvyatoS1/Course_preparation_C#3]

**Comment by SvyatoS1** [comment]
#2

**Comment by PrymakBogdan** [comment]
Вказівники - https://acode.com.ua/urok-84-vkazivnyky/#toc-0
Вказівники і масиви c++ - https://acode.com.ua/urok-86-vkazivnyky-i-masyvy/

**Comment by PrymakBogdan** [comment]
**РЯДКИ**
   Строки обладают рядом возможностей, которые делают их применение дорогостоящим независимо от реализации. Они используют динамическое выделение пам`яти, ведут себя в выражениях, как значения, а их реализация требует большого 
количества копирований.
   Строки удобны, потому что автоматически увеличиваются по мере увеличения хранимого содержимого.
   Это удобнее, чем освобождение памяти вручную, требуемое при 
работе с динамически выделяемым массивом символов в стиле С, как показано в 
следующем коде: 
char* р = ( char * ) mal loc (7) ; 
strcpy (p, "string" ) ; 
free (р) ; 
   Внутренний буфер символов строки, тем не менее, по-прежнему имеет фиксированный размер.
   Любая операция, которая изменяет значение строки, сначала убеждается, что существует только один указатель на эту память. Если же таких указателей несколько, то трансформирующая операция (любая операция, которая может изменить содержимое строки) выделяет новую память и делает копию строки перед ее изменением: 
COWstring s l , s 2 ; 
sl = "hot " ; // sl " hot" 
s2 = s l ; // s2 "hot" (sl и s2 указывают на одну память ) 
s l [O] = ' n ' ; // sl делает новую копию содержимого перед изменением 
// s2 все еще "hot " , но sl == "not "

**Comment by PrymakBogdan** [comment]
Вказівники - https://acode.com.ua/urok-84-vkazivnyky/#toc-0
Вказівники і масиви c++ - https://acode.com.ua/urok-86-vkazivnyky-i-masyvy/

**Comment by PrymakBogdan** [comment]
# Структури
https://acode.com.ua/urok-64-struktury/
## Розміри даних
https://acode.com.ua/urok-33-rozmir-typiv-danyh/
## Вирівнювання структур
Вирівнювання даних у структурах у мові програмування C зазвичай відбувається для оптимізації доступу до полів структур і зменшення відступів, що може підвищити ефективність використання пам'яті та швидкість виконання програми. Проте, вирівнювання також може призвести до деяких проблем, зокрема, великих розмірів структур та втрати пам'яті через вирівнювальні байти.

Основні принципи вирівнювання даних:

1. **Директива `#pragma pack`:**
   - Мова C дозволяє використовувати директиву `#pragma pack`, яка контролює вирівнювання даних у структурах.

     ```c
     #pragma pack(push, 1) // зберегти поточне вирівнювання і встановити 1-байтне
     struct MyStruct {
         char a;
         int b;
     };
     #pragma pack(pop) // відновити попереднє вирівнювання
     ```

   - У цьому прикладі використана директива `#pragma pack`, щоб встановити вирівнювання в один байт для структури `MyStruct`. Однак варто враховувати, що такий підхід може призвести до великого зростання розміру структур та втрати ефективності.

2. **Найбільший тип даних:**
   - Вирівнювання відбувається так, щоб кожен елемент структури розміщувався на границі, яка є кратною розміру найбільшого типу даних у структурі. Наприклад, якщо у структурі є поле типу `double`, то вирівнювання відбудеться на границі розміру `double`.

3. **Вирівнювальні байти:**
   - Зазвичай, кожен елемент структури розміщується на границі, кратній розміру цього елемента. Вирівнювальні байти можуть бути вставлені компілятором, щоб забезпечити вірне вирівнювання. Наприклад, якщо у структурі є `char`, а за ним йде `int`, то може бути вставлено вирівнювальний байт між ними.

4. **Впорядкованість полів:**
   - У деяких компіляторах можливі різні варіанти впорядкованості полів у структурі. Наприклад, може використовуватися "паддінг" (вирівнювання до кратного розміру типу) для забезпечення оптимального доступу до пам'яті.

5. **Розмір структури:**
   - Розмір структури може бути більшим, ніж сума розмірів її полів через вирівнювальні байти та паддінг.

Важливою є обережність при зміні вирівнювання, оскільки це може вплинути на портабельність програми та негативно позначитися на швидкодії та розмірі структур. Вирівнювання зазвичай встановлюється так, щоб забезпечити ефективний доступ до даних на конкретній архітектурі.

## Приклади
Давайте розглянемо кілька прикладів вирівнювання структур у мові програмування C.

### Приклад 1:

```c
#include <stdio.h>

struct ExampleStruct {
    char a;    // 1 byte
    int b;     // 4 bytes (aligned to 4 bytes boundary)
    double c;  // 8 bytes (aligned to 8 bytes boundary)
};

int main() {
    printf("Size of ExampleStruct: %zu bytes\n", sizeof(struct ExampleStruct));
    return 0;
}
```

У цьому прикладі структура `ExampleStruct` має розмір 16 байтів. Це пояснюється тим, що `char` займає 1 байт, потім вирівнюється до границі 4 байтів для `int`, і потім вирівнюється до границі 8 байтів для `double`.

### Приклад 2:

```c
#include <stdio.h>

#pragma pack(push, 1)
struct PackedStruct {
    char a;    // 1 byte
    int b;     // 4 bytes
    double c;  // 8 bytes
};
#pragma pack(pop)

struct NormalStruct {
    char a;    // 1 byte
    int b;     // 4 bytes (aligned to 4 bytes boundary)
    double c;  // 8 bytes (aligned to 8 bytes boundary)
};

int main() {
    printf("Size of PackedStruct: %zu bytes\n", sizeof(struct PackedStruct));
    printf("Size of NormalStruct: %zu bytes\n", sizeof(struct NormalStruct));
    return 0;
}
```

У цьому прикладі використовується директива `#pragma pack` для тимчасового змінювання вирівнювання. Як результат, розмір `PackedStruct` буде менше через відсутність вирівнювальних байтів. Якщо ви не вказуєте жодного вирівнювання, то компілятор використовуватиме значення за замовчуванням для конкретної архітектури.

### Приклад 3:

```c
#include <stdio.h>

struct AlignmentStruct {
    char a;      // 1 byte
    int b;       // 4 bytes (aligned to 4 bytes boundary)
    char c;      // 1 byte
    double d;    // 8 bytes (aligned to 8 bytes boundary)
    short e;     // 2 bytes
};

int main() {
    printf("Size of AlignmentStruct: %zu bytes\n", sizeof(struct AlignmentStruct));
    return 0;
}
```

У цьому прикладі показано, як вирівнювання впливає на розмір структури. Помітте, що після `int b` та `double d` вставляються вирівнювальні байти для вирівнювання до границь 4 та 8 байтів відповідно.
