### ISSUE TITLE
Signals, killing process, types of the signals. + Orphan, zombie, daemon  process.

### ISSUE THREAD

**Issue by PrymakBogdan** [SvyatoS1/Course_preparation_C#31]

**Comment by PrymakBogdan** [comment]
#29

**Comment by SvyatoS1** [comment]
Сигнали, Вбивання Процесів та Типи Сигналів в Linux
- ## 1. Сигнали (Signals)
У системах Unix, таких як Linux, сигнали - це спосіб, за допомогою якого один процес може сповістити інший процес про певну подію, яка відбулася. Сигнали можуть бути викликані різними подіями, такими як помилка, натискання клавіші або запит на завершення роботи.

- ## 2. Вбивання Процесів
У Linux вбивання процесу може бути виконане за допомогою команди kill або інших інструментів управління процесами. Команда kill відправляє сигнал до процесу, що вказується у виклику. Наприклад, для вбивання процесу з ідентифікатором PID використовується команда:
`kill PID`
- ## 3. Типи Сигналів
У Linux існують різні типи сигналів, кожен з яких має своє значення та призначення. Основні типи сигналів включають:

- SIGINT (2): Сигнал, який відправляється до процесу при натисканні комбінації клавіш Ctrl+C. Зазвичай використовується для вимкнення програми.

- SIGKILL (9): Сигнал, який безповоротно завершує процес. Неможливо перехопити або ігнорувати цей сигнал.

- SIGTERM (15): Сигнал, який використовується для відправлення запиту на завершення процесу. Це найбільш часто використовуваний сигнал для вбивання процесів.

- ## 4. Орфанський, Зомбі та Демонічний Процес
Орфанський Процес: Орфанський процес - це процес, який втратив батьківський процес або батьківський процес завершився раніше, ніж дитина. У Linux орфанські процеси переведені під керування процесу з PID 1, який завжди є init або його нащадком.
Основні особливості орфанських процесів включають:

> Перехід під опіку init: Коли батьківський процес завершує свою роботу, усі його дочірні процеси автоматично стають дочірніми процесами процесу з PID 1. Це забезпечує, що немає "вільних" або безпритульних процесів у системі.
> 
> init стає батьком: init стає батьком для орфанських процесів і відповідає за їхню подальшу обробку. init періодично перевіряє систему на наявність орфанських процесів і завершує їх, якщо вони більше не потрібні.
> 
> Звільнення ресурсів: Після того, як орфанський процес завершив свою роботу або був завершений init, всі його ресурси, такі як пам'ять і файли, будуть звільнені.
> 
> Неможливість батьківського контролю: Оскільки батьківський процес не існує, орфанські процеси більше не підлягають контролю або спостереженню з боку свого батька.

- ### Зомбі-процес: Зомбі-процес - це процес, який завершив своє виконання, але має незавершену структуру зберігання інформації про його виконання. Вони неактивні, але ще не були повністю видалені з системи.

- ### Демонічний Процес: Демонічні процеси - це фонові процеси, які працюють у фоновому режимі, зазвичай без прив'язки до конкретного користувача або терміналу. Вони часто використовуються для виконання фонових служб або серверів.

- ## Висновок
Сигнали, вбивання процесів та типи сигналів в Linux є важливими аспектами операційної системи, які дозволяють ефективно управляти процесами та робити їхню взаємодію надійною та безпечною. Розуміння цих концепцій допомагає адміністраторам систем та розробникам створювати стабільні та надійні програми і середовища.
