### ISSUE TITLE
Основні команди Linux + Creating new process: clone, fork, exec, wait. + file permissions: chmod (команда)

### ISSUE THREAD

**Issue by PrymakBogdan** [SvyatoS1/Course_preparation_C#33]

**Comment by PrymakBogdan** [comment]
#29

**Comment by PrymakBogdan** [comment]
# Основні команди Linux

Ось декілька основних команд для роботи з командним рядком Linux. Важливо відзначити, що для більш детальної інформації щодо будь-якої команди можна скористатися допоміжними інструкціями, наприклад, командою `man` (manual).

1. **Показати поточний каталог:**
   ```bash
   pwd
   ```

2. **Список файлів та каталогів в поточному каталозі:**
   ```bash
   ls
   ```

3. **Зміна поточного каталогу:**
   ```bash
   cd <шлях>
   ```

4. **Створення нового каталогу:**
   ```bash
   mkdir <ім'я_каталогу>
   ```

5. **Створення порожнього файлу:**
   ```bash
   touch <ім'я_файлу>
   ```

6. **Копіювання файлу або каталогу:**
   ```bash
   cp <вихідний_шлях> <цільовий_шлях>
   ```

7. **Переміщення або перейменування файлу або каталогу:**
   ```bash
   mv <вихідний_шлях> <цільовий_шлях>
   ```

8. **Видалення файлу або каталогу:**
   ```bash
   rm <ім'я_файлу_або_каталогу>
   ```

9. **Вивід вмісту текстового файлу:**
   ```bash
   cat <ім'я_файлу>
   ```

10. **Редагування текстового файлу (використовуючи текстовий редактор nano):**
    ```bash
    nano <ім'я_файлу>
    ```

11. **Вивід допомоги для команди:**
    ```bash
    man <команда>
    ```

12. **Вивід інформації про систему:**
    ```bash
    uname -a
    ```

13. **Вивід інформації про вільне місце на диску:**
    ```bash
    df -h
    ```

14. **Вивід інформації про використання пам'яті:**
    ```bash
    free -h
    ```

15. **Використання текстового редактору vi (або vim):**
    ```bash
    vi <ім'я_файлу>
    ```

16. **Пошук файлів за певними критеріями:**
    ```bash
    find <каталог> -name <шаблон>
    ```

17. **Архівація файлів та каталогів:**
    ```bash
    tar -czvf <архів.tar.gz> <каталог_або_файл>
    ```

18. **Розархівація архіву:**
    ```bash
    tar -xzvf <архів.tar.gz>
    ```

19. **Встановлення нового програмного забезпечення (використовуючи пакетний менеджер apt):**
    ```bash
    sudo apt-get install <ім'я_пакету>
    ```

20. **Оновлення існуючого програмного забезпечення (використовуючи apt):**
    ```bash
    sudo apt-get update
    sudo apt-get upgrade
    ```

Ці команди представляють лише малу частину можливостей командного рядка Linux. Щоб дізнатися більше про будь-яку команду, використовуйте `man` або переглядайте інтернет-ресурси та документацію.

Докладніше: https://itedu.center/ua/blog/ratings/12-commands-linux/

**Comment by SvyatoS1** [comment]
- # Creating new process: clone, fork, exec, wait. 
Створення нових процесів є важливим аспектом управління процесами в операційній системі Linux. У цьому повному посібнику ми розглянемо основні методи створення нових процесів: clone, fork, exec та wait, і надамо приклади їх використання.
- ## 1. clone
Функція clone є більш гнучким варіантом функції fork. Вона дозволяє контролювати більше параметрів створення процесу, таких як спільні області пам'яті і ресурси.
#define _GNU_SOURCE
#include <sched.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

```
int child_function(void *arg) {
    printf("Child process\n");
    return 0;
}

int main() {
    char *stack = malloc(1024 * 1024); // Стек для нового процесу
    int flags = CLONE_VM | CLONE_FS | CLONE_FILES | CLONE_SIGHAND;

    pid_t pid = clone(child_function, stack + (1024 * 1024), flags, NULL);

    if (pid == -1) {
        perror("clone");
        exit(EXIT_FAILURE);
    }

    printf("Parent process\n");
    return 0;
}
```
- ## 2. fork
fork є одним з найпоширеніших методів створення нового процесу. Він створює точну копію батьківського процесу.
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main() {
    pid_t pid = fork();

    if (pid == -1) {
        perror("fork");
        exit(EXIT_FAILURE);
    } else if (pid == 0) {
        printf("Child process\n");
    } else {
        printf("Parent process\n");
    }

    return 0;
}

- ## 3. exec
Функція exec використовується для заміни поточного процесу новим образом, зчитуючи виконуючий файл з диска.
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main() {
    char *args[] = {"/bin/ls", "-l", NULL};
    execvp(args[0], args);

    // Якщо execvp поверне управління, значить, сталася помилка
    perror("execvp");
    exit(EXIT_FAILURE);
}
```
- ## 4. wait
wait використовується батьківським процесом для очікування завершення дочірнього процесу і отримання статусу завершення.
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>

```
int main() {
    pid_t pid = fork();

    if (pid == -1) {
        perror("fork");
        exit(EXIT_FAILURE);
    } else if (pid == 0) {
        printf("Child process\n");
        exit(EXIT_SUCCESS);
    } else {
        printf("Parent process\n");
        int status;
        wait(&status);
        printf("Child process finished with status: %d\n", WEXITSTATUS(status));
    }

    return 0;
}
```
https://percona.community/blog/2021/01/04/fork-exec-wait-and-exit/
https://cs341.cs.illinois.edu/coursebook/Processes

**Comment by PrymakBogdan** [comment]
# file permissions: chmod

Команда `chmod` в Unix-подібних операційних системах (таких як Linux) використовується для зміни прав доступу до файлів та каталогів. Права доступу визначають, як користувачі можуть взаємодіяти з файлами і каталогами, і вони поділені на три групи: власник (owner), група (group), і інші (others).

### Числовий режим (Numeric Mode):

В числовому режимі, кожні три біти визначають права для конкретної групи. Кожній дії (читання, запис, виконання) надається значення:

- Читання (r) = 4
- Запис (w) = 2
- Виконання (x) = 1

Отже, можна складати ці значення, щоб визначити числовий режим. Наприклад:

- `rwx` = 4 (читання) + 2 (запис) + 1 (виконання) = 7
- `rw-` = 4 (читання) + 2 (запис) + 0 (відсутнє виконання) = 6
- `r--` = 4 (читання) + 0 (відсутнє запису) + 0 (відсутнє виконання) = 4

Приклади використання числового режиму:

```bash
# Надати власнику всі права, групі і іншим тільки право читання та виконання
chmod 711 filename
```

### Символьний режим (Symbolic Mode):

В символьному режимі, команда `chmod` використовує символи для визначення того, які права змінюються. Структура символьного режиму складається з трьох частин:

1. **Кого або що змінити (`u`, `g`, `o`, `a`):**
   - `u` - власник (user)
   - `g` - група (group)
   - `o` - інші (others)
   - `a` - всі (all)

2. **Дія (`+`, `-`, `=`):**
   - `+` - додавання прав
   - `-` - видалення прав
   - `=` - встановлення конкретних прав

3. **Право (`r`, `w`, `x`):**
   - `r` - читання
   - `w` - запис
   - `x` - виконання

Приклади використання символьного режиму:

```bash
# Надати власнику право виконання
chmod u+x filename
```

```bash
# Додати групі право запису, вилучити право виконання власнику
chmod g+w,u-x filename
```

```bash
# Повністю змінити права власника на читання та запис, інших на виконання
chmod u=rw,go=x filename
```

Команда `chmod` також підтримує комбінації декількох змін, а також може бути використана рекурсивно для зміни прав в каталозі та його вмісті.

Популярні значення
400 (-r--------)
Власник має право читання; ніхто інший не має права виконувати ніякі дії
644 (-rw-r-r-)
Усі користувачі мають право читання; власник може редагувати
660 (-rw-rw----)
Власник і група можуть читати і редагувати, решта не мають права виконувати ніякі дії
664 (-rw-rw-r-)
Усі користувачі мають право читання; власник і група можуть редагувати
666 (-rw-rw-rw-)
Усі користувачі можуть читати і редагувати
700 (-rwx------)
Власник може читати, записувати і запускати на виконання; ніхто інший не має права виконувати ніякі дії
744 (-rwxr-r-)
Кожен користувач може читати, власник має право редагувати та запускати на виконання
755 (-rwxr-xr-x)
Кожен користувач має право читати і запускати на виконання; власник може редагувати
777 (-rwxrwxrwx)
Кожен користувач може читати, редагувати та запускати на виконання


Більше: 
https://kb.iu.edu/d/abdb
https://www.freecodecamp.org/news/linux-chmod-chown-change-file-permissions/
