### ISSUE TITLE
З чого складається пам'ять (стек, купа, глобальна)

### ISSUE THREAD

**Issue by PrymakBogdan** [SvyatoS1/Course_preparation_C#4]

**Comment by PrymakBogdan** [comment]
#2

**Comment by SvyatoS1** [comment]
# Пам'ять
- ## Intro
- У мові програмування C++, пам'ять розділяється на кілька областей, включаючи стек, купу та область пам'яті для глобальних змінних.

- ## Стек (Stack)

> - Стек використовується для зберігання локальних змінних функцій та контекстів виклику.
> - Всі автоматично (локально) оголошені змінні, які існують в межах функцій, зберігаються на стеці.
> - Пам'ять у стеці вивільняється автоматично після виходу з області видимості змінної.
> - Операції зі стеком, такі як додавання та видалення змінних, досить швидкі, оскільки це простий механізм.

```
#include <iostream>
#include <stack>

int main() {
    std::stack<int> myStack;

    // Додаємо елементи до стеку
    myStack.push(10);
    myStack.push(20);
    myStack.push(30);

    // Отримуємо розмір стеку
    std::cout << "Size of stack: " << myStack.size() << std::endl;

    // Доступ до вершини стеку без видалення
    std::cout << "Top element: " << myStack.top() << std::endl;

    // Видаляємо верхній елемент
    myStack.pop();

    // Отримуємо новий розмір стеку
    std::cout << "Size of stack after pop: " << myStack.size() << std::endl;

    return 0;
}

```
- Документація: 
https://learn.microsoft.com/ru-ru/cpp/standard-library/stack-class?view=msvc-170
https://en.cppreference.com/w/cpp/container/stack
- Статті:
https://ravesli.com/urok-105-stek-i-kucha/#toc-2
https://itproger.com/ua/spravka/cpp/stack

- ## Купа

> - Купа - це область пам'яті, доступ до якої є динамічним.
> - Завдяки купі можна виділяти пам'ять під об'єкти, які можуть існувати поза межами функцій або навіть після завершення виконання програми.
> - Для роботи з купою використовуються оператори new та delete, або їх відповідники malloc та free.
> - Невірне керування пам'яттю у купі може призвести до проблем, таких як виток пам'яті або переповнення.

```
#include <iostream>

int main() {
    int size;

    std::cout << "Enter the size of the array: ";
    std::cin >> size;

    // Виділення пам'яті у купі для масиву цілих чисел
    int* myArray = new int[size];

    // Ініціалізація масиву
    for (int i = 0; i < size; ++i) {
        myArray[i] = i * 2;
    }

    // Виведення елементів масиву
    std::cout << "Array elements: ";
    for (int i = 0; i < size; ++i) {
        std::cout << myArray[i] << " ";
    }
    std::cout << std::endl;

    // Звільнення пам'яті, виділеної у купі
    delete[] myArray;

    return 0;
}
```
 - ## Глобальна пам'ять

> - Це область, де зберігаються глобальні змінні та статичні змінні, що мають постійне місце в пам'яті протягом всього життєвого циклу програми.
> - Глобальні змінні можуть бути доступні з будь-якої частини програми.
> - Статичні змінні, що визначені в межах функцій, також розміщуються в глобальній пам'яті.

```
#include <iostream>

// Глобальна змінна
int globalVariable = 10;

// Функція, яка використовує глобальну змінну
void printGlobalVariable() {
    std::cout << "Global variable value: " << globalVariable << std::endl;
}

int main() {
    // Виведення значення глобальної змінної
    std::cout << "Global variable value in main: " << globalVariable << std::endl;

    // Зміна значення глобальної змінної
    globalVariable = 20;

    // Виклик функції, що виводить глобальну змінну
    printGlobalVariable();

    return 0;
}
```
- Статті: 
https://acode.com.ua/urok-52-globalni-zminni/
https://purecodecpp.com/uk/archives/2436

**Comment by PrymakBogdan** [comment]
![image](https://github.com/SvyatoS1/Course_preparation_C/assets/152421548/362b6fa3-0451-4cf6-9ad5-157d172484bb)
