### ISSUE TITLE
Звичайні вказівники vs розумні вказівники

### ISSUE THREAD

**Issue by SvyatoS1** [SvyatoS1/Course_preparation_C#6]

**Comment by SvyatoS1** [comment]
#2

**Comment by PrymakBogdan** [comment]
Розумні вказівники - https://www.youtube.com/watch?v=k6GvSgdxwpQ
https://acode.com.ua/urok-197-rozumni-vkazivnyky-i-semantyka-peremishhennya/#toc-3
Ідіома RAII («Resource Acquisition Is Initialization» = «Отримання ресурсу є ініціалізація») — це ідіома ООП, при якій використання ресурсів прив’язується до часу життя об’єктів з автоматичною тривалістю життя.  Ресурс (наприклад, пам’ять, файл або база даних) зазвичай отримується в конструкторі об’єкта . Потім цей ресурс можна використовувати, поки об’єкт живий. Ресурс звільняється в деструкторі при знищенні об’єкта. Основною перевагою RAII є те, що це допомагає запобігти витоку ресурсів (наприклад, пам’яті, яка не була звільнена), так як всі об’єкти, що містять ресурси, автоматично очищаються.
auto_ptr - застаріла і майже неюзабільна
